title: Aditya
description: A Collection Of My Projects
url: "https://adityam23.github.io"

permalink: /projects/:slug/

plugins:
  - jekyll-feed
  - jekyll-seo-tag

exclude:
  - scripts/
  - projects.yml
  - Gemfile
  - Gemfile.lock
  - README.md
  - PUBLISHING.md
  - .github/
  - .aggregated_posts

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
