#!/usr/bin/env ruby
# frozen_string_literal: true
#
# aggregate.rb — pulls portfolio posts from project repos into _posts/
#
# For each repo listed in projects.yml:
#   - clones it shallowly
#   - copies every portfolio/*.md file into _posts/ (dated, slugified)
#   - copies portfolio/assets/ into assets/projects/<repo>/ and rewrites
#     relative image paths in the markdown to point there
#
# Hand-authored posts placed directly in _posts/ are left untouched — only
# files this script generated on a previous run (tracked in .aggregated_posts)
# are cleaned up.

require 'yaml'
require 'fileutils'
require 'date'
require 'tmpdir'
require 'set'

POSTS_DIR    = '_posts'
ASSETS_DIR   = File.join('assets', 'projects') # aggregator-managed asset root
MANIFEST     = '.aggregated_posts'             # posts generated last run
PROJECTS_YML = 'projects.yml'

# Turn an arbitrary filename into a clean URL slug:
# "Query Engine_v2.md" -> "query-engine-v2"
def slugify(name)
  name.downcase.gsub(/[^a-z0-9]+/, '-').gsub(/\A-+|-+\z/, '')
end

# Rewrite relative image paths so they resolve from the site root after the
# assets have been copied into assets/projects/<repo>/.
#   ![alt](assets/x.png)   -> ![alt](/assets/projects/<repo>/x.png)
#   ![alt](./assets/x.png) -> ![alt](/assets/projects/<repo>/x.png)
# Absolute URLs (https://raw.githubusercontent.com/...) are left alone, so the
# raw-URL approach and the bundled-asset approach can coexist in one post.
def rewrite_image_paths(content, repo_slug)
  content.gsub(%r{!\[([^\]]*)\]\((?:\./)?assets/([^)]+)\)}) do
    "![#{Regexp.last_match(1)}](/#{ASSETS_DIR}/#{repo_slug}/#{Regexp.last_match(2)})"
  end
end

# --- Setup ------------------------------------------------------------------

FileUtils.mkdir_p(POSTS_DIR)

# Remove posts generated by the previous run (but NOT hand-authored ones).
if File.exist?(MANIFEST)
  File.readlines(MANIFEST, chomp: true).each do |path|
    File.delete(path) if File.exist?(path)
  end
end

# assets/projects/ is entirely aggregator-owned — safe to wipe wholesale so
# stale images from removed projects don't pile up.
FileUtils.rm_rf(ASSETS_DIR)
FileUtils.mkdir_p(ASSETS_DIR)

projects = YAML.load_file(PROJECTS_YML).fetch('projects')

generated   = []        # post files written this run -> manifest
seen_dests  = Set.new   # detect slug collisions across all repos
post_count  = 0
repo_count  = 0

# --- Main loop --------------------------------------------------------------

Dir.mktmpdir do |tmp|
  projects.each do |project|
    repo      = project.fetch('repo')
    branch    = project['branch'] || 'main'
    repo_slug = slugify(repo.split('/').last)

    puts "→ #{repo} @ #{branch}"

    clone_dir = File.join(tmp, repo_slug)
    ok = system('git', 'clone', '--depth=1', '--branch', branch, '--quiet',
                "https://github.com/#{repo}.git", clone_dir)
    unless ok
      warn "  clone failed — skipping"
      next
    end

    portfolio_dir = File.join(clone_dir, 'portfolio')
    posts = Dir.glob(File.join(portfolio_dir, '*.md')).sort
    if posts.empty?
      warn "  no portfolio/*.md — skipping"
      next
    end

    repo_count += 1

    # Copy this repo's assets (if any) into assets/projects/<repo>/.
    src_assets = File.join(portfolio_dir, 'assets')
    if Dir.exist?(src_assets)
      dest_assets = File.join(ASSETS_DIR, repo_slug)
      FileUtils.mkdir_p(dest_assets)
      FileUtils.cp_r(Dir.glob(File.join(src_assets, '*')), dest_assets)
      puts "  copied assets/ -> #{dest_assets}"
    end

    posts.each do |src|
      content = File.read(src)

      # Skip anything that isn't actually a Jekyll post (no front matter).
      unless content.lstrip.start_with?('---')
        warn "  #{File.basename(src)}: no front matter — skipping"
        next
      end

      slug = slugify(File.basename(src, '.md'))

      # Date drives the filename and (with permalink config) the URL, so a
      # missing date means the URL would change every build. Warn loudly.
      date = content[/^date:\s*([\d-]{10})/, 1]
      if date.nil?
        date = Date.today.strftime('%Y-%m-%d')
        warn "  #{File.basename(src)}: no 'date:' in front matter — using #{date}"
      end

      dest = File.join(POSTS_DIR, "#{date}-#{slug}.md")

      # Two posts (anywhere across all repos) resolving to the same filename
      # would silently overwrite each other. Catch it.
      if seen_dests.include?(dest)
        warn "  COLLISION: #{dest} already written this run — skipping " \
             "#{repo}/#{File.basename(src)}. Rename the file to fix."
        next
      end
      seen_dests << dest

      content = rewrite_image_paths(content, repo_slug)

      File.write(dest, content)
      generated << dest
      seen_dests << dest
      post_count += 1
      puts "  wrote #{dest}"
    end
  end
end

# --- Finish -----------------------------------------------------------------

File.write(MANIFEST, generated.join("\n"))

puts
puts "Done: #{post_count} post(s) from #{repo_count} repo(s)."
puts "Tracked #{generated.length} generated file(s) in #{MANIFEST}."
